version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      - echo Installing dependencies...
      - pip install -r requirements.txt
      - pip install pytest

  pre_build:
    commands:
      - echo Logging into ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $REPOSITORY_URI
      - echo Running tests...
      - pytest || echo "No tests found, skipping..."

  build:
    commands:
      - echo Building Docker image...
      - docker build -t task-manager .
      - docker tag task-manager:latest $REPOSITORY_URI:latest

  post_build:
    commands:
      - echo Pushing image to ECR...
      - docker push $REPOSITORY_URI:latest
